### ISSUE TITLE
NodeCrawler fails if a parent page is disabled

### ISSUE THREAD

**Issue by paavo** [Sebobo/Shel.Crawler#5]
The crawler fails with the error `No base URI could be provided.` if a parents page is disabled. 

```
- Neos Site
- - Parent page (disabled)
- - - Child page <- throws Error while crawling
```

![image](https://user-images.githubusercontent.com/1118783/205645216-c6be6fed-a808-491e-a14e-9c9e2dc39297.png)

```
Crawling node: "Passwort geschützte Seite"
No base URI could be provided.
This probably means a call was made outside of an HTTP request and a base
URI was neither configured nor specified as $fallbackRequest.

  Type: Neos\Flow\Http\Exception
```

**Comment by paavo** [comment]
Any hint if there is an easy way to check if a parents site is hidden @Sebobo?

**Comment by paavo** [comment]
Ok, this is maybe more a general problem in LinkingService of Neos.Neos 🤔

**Comment by Sebobo** [comment]
We should prevent crawling any inaccessible pages and add more error handling probably.

**Comment by paavo** [comment]
> We should prevent crawling any inaccessible pages and add more error handling probably.
Oh yes @Sebobo 

As an alternative i added the PR https://github.com/Sebobo/Shel.Crawler/pull/6 to use RobotsTxt Crawling instead.
