### ISSUE TITLE
Error with PHP 7.4

### ISSUE THREAD

**Issue by paavo** [Sebobo/Shel.Crawler#8]
Looks like latest update does not work with PHP 7.3. 
Can we fix this or do we adjust dependencies @Sebobo?

```Fatal error: Class Shel\Crawler\Http\CrawlerRequestHandler contains 2
abstract methods and must therefore be declared abstract or implement the
remaining methods
```

**Comment by Sebobo** [comment]
Can you update to PHP 7.4? I personally don't test with it anymore and don't really want to.

**Comment by paavo** [comment]
Oh, im sorry.. this project runs on PHP 7.4 (i mixed it with neos 7.3 🙈 )

**Comment by Sebobo** [comment]
Do you then have a few more details?

**Comment by paavo** [comment]
> Do you then have a few more details?
Here you go @Sebobo 

```
Fatal error: Class Shel\Crawler\Http\CrawlerRequestHandler contains 2
abstract methods and must therefore be declared abstract or implement the
remaining methods
(Neos\Flow\Http\HttpRequestHandlerInterface::getHttpResponse,
Neos\Flow\Http\HttpRequestHandlerInterface::getComponentContext) in
.../Packages/Plugins/Shel.Crawler/Classes/Http/CrawlerRequestHandler.php
on line 10
```

**Comment by Sebobo** [comment]
😔 need to check how I can make it compatible with both versions as the interface is different...
